### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#175]
Here the list of missing tests:
- [x] account/register/register.component.spec.ts -> done in #207 
- [x] account/register/register.service.spec.ts -> done in #207 
- [x] account/reset-password/reset-password.component.spec.ts
- [x] account/activate/activate.component.spec.ts
- [x] account/login-modal.service.spec.ts
- [x] account/account.service.spec.ts -> done alongside oAuth2 support
- [x] admin/audits/audits.service.spec.ts -> Already fully tested through component
- [x] admin/configuration/configuration.service.spec.ts
- [x] admin/health/health-modal.component.spec.ts
- [x] admin/logs/logs.service.spec.ts -> Already fully tested through component
- [x] admin/metrics/metrics.service.spec.ts -> Already fully tested through component
- [x] admin/user-management/user-management.service.spec.ts -> Already fully tested through 
component
- [x] core/error/error.component.spec.ts
- [x] shared/alert/alert.service.spec.ts
- [x] core/home/home.component.spec.ts
- [x] core/jhi-navbar/jhi-navbar.component.spec.ts
- [x] admin/tracker/tracker.component.spec.ts -> done by https://github.com/jhipster/jhipster-vuejs/pull/147
- [x] admin/tracker/tracker.service.spec.ts -> done by https://github.com/jhipster/jhipster-vuejs/pull/147
- [x] app/shared/config/axios-interceptor.spec.ts -> done in #339 
- [x] app/shared/config/formatter.spec.ts -> done in #339 
- [x] app/shared/config/data-utils.service.spec.ts -> done in #339 

I wonder if it should be done in separated PR or in one PR for all.

**Comment by atomfrede** [comment]
I would do it in separate PRs.

**Comment by pascalgrimaud** [comment]
Ok, I edited my original post, so we can check each file when it's done

**Comment by hdurix** [comment]
`tracker.component.spec.ts` & `tracker.service.spec.ts` have been added here: https://github.com/jhipster/jhipster-vuejs/pull/147.

**Comment by hdurix** [comment]
I think you could remove all the `service.spec` from the list.

Sometimes, a test for the service is better (like for `tracker.service.spec.ts` because it contains a lot of logic), but we should choose on a case by case basis.
Because sometimes, it's ok to test the service through the component. For instance, the `admin/audits/audits.service.spec.ts` is already 100% covered by `admin/audits/audits.component.spec.ts` and that's perfectly fine.

**Comment by pascalgrimaud** [comment]
@hdurix : I'm ok, don't hesitate to edit my ticket !

**Comment by richard-francois** [comment]
Hello, i propose to implement this missing tests :+1: 

account/login-modal.service.spec.ts
account/principal.spec.ts

if there is no objection, I will begin to work on it tonight..

**Comment by sahbi-ktifa** [comment]
Please do not work on principal, as I'm working on it.

**Comment by richard-francois** [comment]
Ok no problem

**Comment by richard-francois** [comment]
I propose to go working on tests uppon app/shared/config/formatter.spec.ts

**Comment by sahbi-ktifa** [comment]
Once #339 is merged, I think we are done here !

**Comment by pascalgrimaud** [comment]
everything is done here, so I'm closing this

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : you can claim the bounty, as you did nearly all part

**Comment by sahbi-ktifa** [comment]
Bounty claimed here : https://opencollective.com/generator-jhipster/expenses/7640

Guys, I've claimed this one, but as some of you have participated to this issue, let me know, I'll share the bounty!

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : share the :beer: !
